In [17]:
import sys
print(sys.executable)
print(sys.path)
import pandapower as pp

D:\Users\xjj\anaconda3\envs\pytorch\python.exe
['D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\python310.zip', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\DLLs', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\lib', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch', '', 'C:\\Users\\xjj\\AppData\\Roaming\\Python\\Python310\\site-packages', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\lib\\site-packages', 'D:\\Users\\xjj\\AppData\\Local\\Programs\\python_ws\\cleanrl-master', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\lib\\site-packages\\win32', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\lib\\site-packages\\win32\\lib', 'D:\\Users\\xjj\\anaconda3\\envs\\pytorch\\lib\\site-packages\\Pythonwin']

In [2]:
import gymnasium as gym
import opfgym
from opfgym.envs.eco_dispatch import EcoDispatch
from opfgym.envs.voltage_control import VoltageControl

<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

In [3]:
if 'EcoDispatch-v0' not in gym.envs.registry:
    gym.envs.registration.register(
        id='EcoDispatch-v0',  # 为环境指定一个唯一的 ID
        entry_point='opfgym.envs.eco_dispatch:EcoDispatch',  # 告诉 gym 如何找到这个环境类
    )
if 'VoltageControl-v0' not in gym.envs.registry:
    gym.envs.registration.register(
        id='VoltageControl-v0',
        entry_point='opfgym.envs.voltage_control:VoltageControl',
    )

In [4]:
env = gym.make("VoltageControl-v0")
obs, info = env.reset()
action = env.action_space.sample()
next_obs, reward, terminated, truncated, info = env.step(action)

D:\Users\xjj\anaconda3\envs\pytorch\lib\site-packages\gymnasium\utils\passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
D:\Users\xjj\anaconda3\envs\pytorch\lib\site-packages\gymnasium\utils\passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
D:\Users\xjj\anaconda3\envs\pytorch\lib\site-packages\gymnasium\utils\passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
D:\Users\xjj\anaconda3\envs\pytorch\lib\site-packages\gymnasium\utils\passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")

In [5]:
env.observation_space.shape

(442,)

In [6]:
env.observation_space.dtype

dtype('float32')

In [7]:
env.action_space.shape

(14,)

In [8]:
env.action_space.low

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [9]:
env.action_space.high

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

In [10]:
env.observation_space

Box([ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  3.2334354e-02
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  0.0000000e+00 -9.0185918e-02
 -9.0185918e-02 -9.0185918e-02 -9.0185918e-02 -9.0185918e-02
 -9.0185918e-02 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02
 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02
 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02
 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02
 -4.5585733e-02 -4.5585733e-02 -4.5585733e-02 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03
 -8.2323030e-03 -8.2323030e-03 -8.2323030e-03 -5.6000330e-02
 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02
 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02
 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02
 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02
 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02 -5.6000330e-02
 -5.6000330e-02 -5.6000330e-02 -1.5482551e+00 -1.5327051e+00
 -2.6140599e+00 -2.3074627e+00  1.8600991e-02  1.4877063e-02
  2.1410804e-02  2.1410804e-02  1.2135026e-02  1.2135026e-02
  2.1410804e-02  8.5219741e-03  1.2135026e-02  9.0015279e-03
  1.2135026e-02  2.1410804e-02  2.1410804e-02  2.1410804e-02
  2.1410804e-02  2.1410804e-02  1.2135026e-02  1.2135026e-02
  2.1410804e-02  2.1410804e-02  1.2135026e-02  9.0015279e-03
  9.0015279e-03  1.2135026e-02  1.2135026e-02  1.2135026e-02
  9.0015279e-03  8.5219741e-03  8.5219741e-03  9.0015279e-03
  1.2135026e-02  1.2135026e-02  9.0015279e-03  8.5219741e-03
  8.5219741e-03  8.5219741e-03  8.5219741e-03  8.5219741e-03
  8.5219741e-03  1.2135026e-02  9.0015279e-03  1.2135026e-02
  9.0015279e-03  8.5219741e-03  1.2135026e-02  8.5219741e-03
  1.2135026e-02  1.2135026e-02  1.2135026e-02  1.2135026e-02
  1.2135026e-02  8.5219741e-03  8.5219741e-03  8.5219741e-03
  1.2135026e-02  9.0015279e-03  1.2135026e-02  1.2135026e-02
  1.2135026e-02  9.0015279e-03  8.5219741e-03  7.3022041e-03
  7.3022041e-03  7.3022041e-03  8.5219741e-03  7.3022041e-03
  2.1410804e-02  1.2135026e-02  9.0015279e-03  9.0015279e-03
  7.3022041e-03  8.5219741e-03  8.5219741e-03  8.5219741e-03
  8.5219741e-03  1.2135026e-02  2.1410804e-02  2.1410804e-02
  8.5219741e-03  8.5219741e-03  9.0015279e-03  9.0015279e-03
  1.2135026e-02  1.4877063e-02  2.1410804e-02  2.1410804e-02
  2.1410804e-02  2.1410804e-02  2.1410804e-02  2.1410804e-02
  1.2135026e-02  2.1410804e-02  1.2135026e-02  1.2135026e-02
  2.1410804e-02  1.2135026e-02  9.0015279e-03  2.1410804e-02
  1.2135026e-02  1.2135026e-02  2.1410804e-02  1.2135026e-02
  8.5219741e-03  8.5219741e-03  1.2135026e-02  9.0015279e-03
  1.2135026e-02  8.5219741e-03  7.3022041e-03  9.0015279e-03
  9.0015279e-03  0.0000000e+00  0.0000000e+00  0.0000000e+00
  0.0000000e+00  0.0000000e+00  6.6244346e-03 -2.5788897e-03
 -6.7726360e-04 -6.7726360e-04  6.7973777e-04  6.7973777e-04
 -6.7726360e-04 -8.3272322e-04  6.7973777e-04 -2.7701759e-03
  6.7973777e-04 -6.7726360e-04 -6.7726360e-04 -6.7726360e-04
 -6.7726360e-04 -6.7726360e-04  6.7973777e-04  6.7973777e-04
 -6.7726360e-04 -6.7726360e-04  6.7973777e-04 -2.7701759e-03
 -2.7701759e-03  6.7973777e-04  6.7973777e-04  6.7973777e-04
 -2.7701759e-03 -8.3272322e-04 -8.3272322e-04 -2.7701759e-03
  6.7973777e-04  6.7973777e-04 -2.7701759e-03 -8.3272322e-04
 -8.3272322e-04 -8.3272322e-04 -8.3272322e-04 -8.3272322e-04
 -8.3272322e-04  6.7973777e-04 -2.7701759e-03  6.7973777e-04
 -2.7701759e-03 -8.3272322e-04  6.7973777e-04 -8.3272322e-04
  6.7973777e-04  6.7973777e-04  6.7973777e-04  6.7973777e-04
  6.7973777e-04 -8.3272322e-04 -8.3272322e-04 -8.3272322e-04
  6.7973777e-04 -2.7701759e-03  6.7973777e-04  6.7973777e-04
  6.7973777e-04 -2.7701759e-03 -8.3272322e-04  4.1519306e-03
  4.1519306e-03  4.1519306e-03 -8.3272322e-04  4.1519306e-03
 -6.7726360e-04  6.7973777e-04 -2.7701759e-03 -2.7701759e-03
  4.1519306e-03 -8.3272322e-04 -8.3272322e-04 -8.3272322e-04
 -8.3272322e-04  6.7973777e-04 -6.7726360e-04 -6.7726360e-04
 -8.3272322e-04 -8.3272322e-04 -2.7701759e-03 -2.7701759e-03
  6.7973777e-04 -2.5788897e-03 -6.7726360e-04 -6.7726360e-04
 -6.7726360e-04 -6.7726360e-04 -6.7726360e-04 -6.7726360e-04
  6.7973777e-04 -6.7726360e-04  6.7973777e-04  6.7973777e-04
 -6.7726360e-04  6.7973777e-04 -2.7701759e-03 -6.7726360e-04
  6.7973777e-04  6.7973777e-04 -6.7726360e-04  6.7973777e-04
 -8.3272322e-04 -8.3272322e-04  6.7973777e-04 -2.7701759e-03
  6.7973777e-04 -8.3272322e-04  4.1519306e-03 -2.7701759e-03
 -2.7701759e-03  0.0000000e+00  1.0988000e-04  0.0000000e+00
  0.0000000e+00  0.0000000e+00], [1.48899829e+00 7.99044371e-02 1.05922319e-01 1.05922319e-01
 3.91710130e-03 3.91710130e-03 1.05922319e-01 1.34799212e-01
 3.91710130e-03 1.38615668e-01 3.91710130e-03 1.05922319e-01
 1.05922319e-01 1.05922319e-01 1.05922319e-01 1.05922319e-01
 3.91710130e-03 3.91710130e-03 1.05922319e-01 1.05922319e-01
 3.91710130e-03 1.38615668e-01 1.38615668e-01 3.91710130e-03
 3.91710130e-03 3.91710130e-03 1.38615668e-01 1.34799212e-01
 1.34799212e-01 1.38615668e-01 3.91710130e-03 3.91710130e-03
 1.38615668e-01 1.34799212e-01 1.34799212e-01 1.34799212e-01
 1.34799212e-01 1.34799212e-01 1.34799212e-01 3.91710130e-03
 1.38615668e-01 3.91710130e-03 1.38615668e-01 1.34799212e-01
 3.91710130e-03 1.34799212e-01 3.91710130e-03 3.91710130e-03
 3.91710130e-03 3.91710130e-03 3.91710130e-03 1.34799212e-01
 1.34799212e-01 1.34799212e-01 3.91710130e-03 1.38615668e-01
 3.91710130e-03 3.91710130e-03 3.91710130e-03 1.38615668e-01
 1.34799212e-01 2.66098648e-01 2.66098648e-01 2.66098648e-01
 1.34799212e-01 2.66098648e-01 1.05922319e-01 3.91710130e-03
 1.38615668e-01 1.38615668e-01 2.66098648e-01 1.34799212e-01
 1.34799212e-01 1.34799212e-01 1.34799212e-01 3.91710130e-03
 1.05922319e-01 1.05922319e-01 1.34799212e-01 1.34799212e-01
 1.38615668e-01 1.38615668e-01 3.91710130e-03 7.99044371e-02
 1.05922319e-01 1.05922319e-01 1.05922319e-01 1.05922319e-01
 1.05922319e-01 1.05922319e-01 3.91710130e-03 1.05922319e-01
 3.91710130e-03 3.91710130e-03 1.05922319e-01 3.91710130e-03
 1.38615668e-01 1.05922319e-01 3.91710130e-03 3.91710130e-03
 1.05922319e-01 3.91710130e-03 1.34799212e-01 1.34799212e-01
 3.91710130e-03 1.38615668e-01 3.91710130e-03 1.34799212e-01
 2.66098648e-01 1.38615668e-01 1.38615668e-01 5.35661936e-01
 4.75449152e-02 7.43263215e-02 3.77210808e+00 7.60718659e-02
 9.20000017e-01 2.08458591e+00 8.75257730e-01 1.98532009e+00
 1.68752205e+00 9.92660046e+00 9.92660046e+00 9.01859179e-02
 9.01859179e-02 9.01859179e-02 9.01859179e-02 9.01859179e-02
 9.01859179e-02 4.55857329e-02 4.55857329e-02 4.55857329e-02
 4.55857329e-02 4.55857329e-02 4.55857329e-02 4.55857329e-02
 4.55857329e-02 4.55857329e-02 4.55857329e-02 4.55857329e-02
 4.55857329e-02 4.55857329e-02 4.55857329e-02 4.55857329e-02
 4.55857329e-02 4.55857329e-02 4.55857329e-02 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 8.23230296e-03
 8.23230296e-03 8.23230296e-03 8.23230296e-03 5.60003296e-02
 5.60003296e-02 5.60003296e-02 5.60003296e-02 5.60003296e-02
 5.60003296e-02 5.60003296e-02 5.60003296e-02 5.60003296e-02
 5.60003296e-02 5.60003296e-02 5.60003296e-02 5.60003296e-02
 5.60003296e-02 5.60003296e-02 5.60003296e-02 5.60003296e-02
 5.60003296e-02 5.60003296e-02 5.60003296e-02 5.60003296e-02
 5.60003296e-02 5.60003296e-02 1.54825509e+00 1.53270507e+00
 2.61405993e+00 2.30746269e+00 3.38600010e-01 1.91497922e-01
 1.99259415e-01 1.99259415e-01 1.21054731e-01 1.21054731e-01
 1.99259415e-01 8.44704807e-02 1.21054731e-01 2.18244299e-01
 1.21054731e-01 1.99259415e-01 1.99259415e-01 1.99259415e-01
 1.99259415e-01 1.99259415e-01 1.21054731e-01 1.21054731e-01
 1.99259415e-01 1.99259415e-01 1.21054731e-01 2.18244299e-01
 2.18244299e-01 1.21054731e-01 1.21054731e-01 1.21054731e-01
 2.18244299e-01 8.44704807e-02 8.44704807e-02 2.18244299e-01
 1.21054731e-01 1.21054731e-01 2.18244299e-01 8.44704807e-02
 8.44704807e-02 8.44704807e-02 8.44704807e-02 8.44704807e-02
 8.44704807e-02 1.21054731e-01 2.18244299e-01 1.21054731e-01
 2.18244299e-01 8.44704807e-02 1.21054731e-01 8.44704807e-02
 1.21054731e-01 1.21054731e-01 1.21054731e-01 1.21054731e-01
 1.21054731e-01 8.44704807e-02 8.44704807e-02 8.44704807e-02
 1.21054731e-01 2.18244299e-01 1.21054731e-01 1.21054731e-01
 1.21054731e-01 2.18244299e-01 8.44704807e-02 7.54142031e-02
 7.54142031e-02 7.54142031e-02 8.44704807e-02 7.54142031e-02
 1.99259415e-01 1.21054731e-01 2.18244299e-01 2.18244299e-01
 7.54142031e-02 8.44704807e-02 8.44704807e-02 8.44704807e-02
 8.44704807e-02 1.21054731e-01 1.99259415e-01 1.99259415e-01
 8.44704807e-02 8.44704807e-02 2.18244299e-01 2.18244299e-01
 1.21054731e-01 1.91497922e-01 1.99259415e-01 1.99259415e-01
 1.99259415e-01 1.99259415e-01 1.99259415e-01 1.99259415e-01
 1.21054731e-01 1.99259415e-01 1.21054731e-01 1.21054731e-01
 1.99259415e-01 1.21054731e-01 2.18244299e-01 1.99259415e-01
 1.21054731e-01 1.21054731e-01 1.99259415e-01 1.21054731e-01
 8.44704807e-02 8.44704807e-02 1.21054731e-01 2.18244299e-01
 1.21054731e-01 8.44704807e-02 7.54142031e-02 2.18244299e-01
 2.18244299e-01 2.09199995e-01 8.47000033e-02 2.34099999e-01
 2.44000003e-01 1.48999998e-02 1.24603055e-01 6.61284029e-02
 7.65394047e-02 7.65394047e-02 3.48185226e-02 3.48185226e-02
 7.65394047e-02 3.21363918e-02 3.48185226e-02 8.18881914e-02
 3.48185226e-02 7.65394047e-02 7.65394047e-02 7.65394047e-02
 7.65394047e-02 7.65394047e-02 3.48185226e-02 3.48185226e-02
 7.65394047e-02 7.65394047e-02 3.48185226e-02 8.18881914e-02
 8.18881914e-02 3.48185226e-02 3.48185226e-02 3.48185226e-02
 8.18881914e-02 3.21363918e-02 3.21363918e-02 8.18881914e-02
 3.48185226e-02 3.48185226e-02 8.18881914e-02 3.21363918e-02
 3.21363918e-02 3.21363918e-02 3.21363918e-02 3.21363918e-02
 3.21363918e-02 3.48185226e-02 8.18881914e-02 3.48185226e-02
 8.18881914e-02 3.21363918e-02 3.48185226e-02 3.21363918e-02
 3.48185226e-02 3.48185226e-02 3.48185226e-02 3.48185226e-02
 3.48185226e-02 3.21363918e-02 3.21363918e-02 3.21363918e-02
 3.48185226e-02 8.18881914e-02 3.48185226e-02 3.48185226e-02
 3.48185226e-02 8.18881914e-02 3.21363918e-02 3.81538495e-02
 3.81538495e-02 3.81538495e-02 3.21363918e-02 3.81538495e-02
 7.65394047e-02 3.48185226e-02 8.18881914e-02 8.18881914e-02
 3.81538495e-02 3.21363918e-02 3.21363918e-02 3.21363918e-02
 3.21363918e-02 3.48185226e-02 7.65394047e-02 7.65394047e-02
 3.21363918e-02 3.21363918e-02 8.18881914e-02 8.18881914e-02
 3.48185226e-02 6.61284029e-02 7.65394047e-02 7.65394047e-02
 7.65394047e-02 7.65394047e-02 7.65394047e-02 7.65394047e-02
 3.48185226e-02 7.65394047e-02 3.48185226e-02 3.48185226e-02
 7.65394047e-02 3.48185226e-02 8.18881914e-02 7.65394047e-02
 3.48185226e-02 3.48185226e-02 7.65394047e-02 3.48185226e-02
 3.21363918e-02 3.21363918e-02 3.48185226e-02 8.18881914e-02
 3.48185226e-02 3.21363918e-02 3.81538495e-02 8.18881914e-02
 8.18881914e-02 7.91573003e-02 3.92673276e-02 8.03905502e-02
 9.65303332e-02 5.90000022e-03], (442,), float32)

In [12]:
env.action_space

Box(0.0, 1.0, (14,), float32)

In [13]:
net = env.get_wrapper_attr('net')

In [14]:
net

This pandapower network includes the following parameter tables:
   - bus (122 elements)
   - load (116 elements)
   - sgen (123 elements)
   - storage (87 elements)
   - switch (248 elements)
   - ext_grid (1 element)
   - line (126 elements)
   - trafo (2 elements)
   - measurement (42 elements)
   - poly_cost (15 elements)
   - substation (1 element)
   - loadcases (6 elements)
 and the following results tables:
   - res_bus (122 elements)
   - res_line (126 elements)
   - res_trafo (2 elements)
   - res_ext_grid (1 element)
   - res_load (116 elements)
   - res_sgen (123 elements)
   - res_storage (87 elements)
   - res_switch (248 elements)

In [15]:
net.bus

,name,vn_kv,type,zone,in_service,geo,min_vm_pu,max_vm_pu,subnet,substation,voltLvl
0,HV1 Bus 19,110.0,db,NaN,True,"{""type"":""Point"", ""coordinates"":[11.812, 53.4247]}",0.95,1.05,HV1_MV2.101,HV1_MV2.101_Substation,3
1,HV1 Bus 20,110.0,db,NaN,True,"{""type"":""Point"", ""coordinates"":[11.812, 53.4247]}",0.95,1.05,HV1_MV2.101,HV1_MV2.101_Substation,3
2,MV2.101 busbar1.1,20.0,b,NaN,True,"{""type"":""Point"", ""coordinates"":[11.812, 53.4247]}",0.95,1.05,MV2.101,HV1_MV2.101_Substation,5
3,MV2.101 busbar1.2,20.0,b,NaN,True,"{""type"":""Point"", ""coordinates"":[11.812, 53.4247]}",0.95,1.05,MV2.101,HV1_MV2.101_Substation,5
4,MV2.101 Bus 4,20.0,b,NaN,True,"{""type"":""Point"", ""coordinates"":[11.8149, 53.42...",0.95,1.05,MV2.101_LV6.201,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...
117,MV2.101 Bus 117,20.0,n,NaN,True,"{""type"":""Point"", ""coordinates"":[11.7892, 53.43...",0.95,1.05,MV2.101_Feeder3,NaN,5
118,MV2.101 Bus 118,20.0,n,NaN,True,"{""type"":""Point"", ""coordinates"":[11.7937, 53.44...",0.95,1.05,MV2.101_Feeder2,NaN,5
119,MV2.101 Bus 119,20.0,n,NaN,True,"{""type"":""Point"", ""coordinates"":[11.7897, 53.449]}",0.95,1.05,MV2.101_Feeder2,NaN,5
120,MV2.101 Bus 120,20.0,n,NaN,True,"{""type"":""Point"", ""coordinates"":[11.7865, 53.43...",0.95,1.05,MV2.101_Feeder10,NaN,5
121,MV2.101 Bus 121,20.0,n,NaN,True,"{""type"":""Point"", ""coordinates"":[11.7837, 53.43...",0.95,1.05,MV2.101_Feeder10,NaN,5

In [18]:
pp.to_excel(net, 'VoltageControl-v0_net.xlsx', include_empty_tables=True, include_results=True)
print("网络数据已导出到 'VoltageControl-v0_net.xlsx'")

网络数据已导出到 'VoltageControl-v0_net.xlsx'

In [19]:
net.poly_cost

,element,et,cp0_eur,cp1_eur_per_mw,cp2_eur_per_mw2,cq0_eur,cq1_eur_per_mvar,cq2_eur_per_mvar2,min_cq2_eur_per_mvar2,max_cq2_eur_per_mvar2
0,0,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
1,111,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
2,114,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
3,116,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
4,117,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
5,118,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
6,119,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
7,120,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
8,121,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
9,122,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
10,83,storage,0.0,-0.03,0.0,0.0,0.0,0.0,0,0.03
11,84,storage,0.0,-0.03,0.0,0.0,0.0,0.0,0,0.03
12,85,storage,0.0,-0.03,0.0,0.0,0.0,0.0,0,0.03
13,86,storage,0.0,-0.03,0.0,0.0,0.0,0.0,0,0.03
14,0,ext_grid,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03

In [21]:
dict = net.poly_cost['et'].isin(['gen', 'sgen','ext_grid'])

In [22]:
dict

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12    False
13    False
14     True
Name: et, dtype: bool

In [32]:
cost_table = net.poly_cost[net.poly_cost['et'].isin(['gen', 'sgen','ext_grid'])].copy()

In [33]:
cost_table

,element,et,cp0_eur,cp1_eur_per_mw,cp2_eur_per_mw2,cq0_eur,cq1_eur_per_mvar,cq2_eur_per_mvar2,min_cq2_eur_per_mvar2,max_cq2_eur_per_mvar2
0,0,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
1,111,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
2,114,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
3,116,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
4,117,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
5,118,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
6,119,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
7,120,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
8,121,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
9,122,sgen,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03
14,0,ext_grid,0.0,0.03,0.0,0.0,0.0,0.0,0,0.03

In [37]:
len(cost_table)

11